### PR TITLE
Switch to new hapi namespace

### PR DESCRIPTION
**Pull request by lenovouser**

### CODE REVIEW

**Comment by SimonSchick** [comment]
Thanks for the contribution!
Please note that we don't develop much with hapi and probably won't be using the namespaced version ourselves.

Please also note that there are some issues with the way the the rate limit callbacks are handled, mostly due to bad typings in `limitus`.

If you have some free time it would be cool if you want to fork this project and eventually get it into the hapi org since I'm not really aware of any other ratelimiting framework for hapi!

**Comment by lenovouser** [comment]
> If you have some free time it would be cool if you want to fork this project and eventually get it into the hapi org since I'm not really aware of any other ratelimiting framework for hapi!

Yeah, this sounds like a good idea. Even though I am not too sure about it being accepted into hapi because Eran doesn't seem to want TypeScript only modules. That's my impression at least.

**Comment by SimonSchick** [comment]
I'm no longer with Mixer (and neither is @connor4312), @Doridian would you kindly merge this? 😄

**Comment by midnightcodr** [comment]
Can we have this pull request merged? I have most of my hapi related stuff using name spacing version, it doesn't make sense that I have to install two versions of hapi modules (boom, joi) due to this module.

**Comment by midnightcodr** [comment]
Awesome! Thanks @Doridian.

**Pull request merged**
